---
title: "Dual bruk av tobakksprodukt og/eller vape"
format:
  html:
    toc: true
    toc-location: left
    fig-cap-location: bottom
execute:
 echo: false
---


```{r}
#| label: setup
#| warning: false

library("highdir")
source("c:/Users/ykama/Git-hdir/tot/reports/tobakkstat2025.R")

gender <- data.table(
  kjonn = c("1", "2", "Total"),
  kjonnCat = c("Menn", "Kvinner", "Total")
)

```

## Figur 18 

```{r}

dualDT[gender, gender := i.kjonnCat, on = "kjonn"]

spec_dual <- hd_spec(data = dualDT, x = "gender", y = "percentage", group = "type", n = "n_outcome_1")

opts_dual <- hd_opts(title = "Kombinert bruk av fleire vape- eller tobakksprodukt blant kvinner og menn 16–79 år, 2025",
                     subtitle = "Bruker to eller tre ulike tobakksprodukt og/eller vape dagleg eller av og til",
                     caption = "Helsedirektoratet, tal frå Rus- og tobakksundersøkinga (SSB)",
                     yint = 5,
                     ysuffix = "%",
                     ylab = NULL,
                     xlab = NULL,
                     ylim = c(0,25))

hd_make(spec_dual, "column", opts = opts_dual)

```

## Figur 19



```{r}

title = "Andel som kombinerer bruk av to produkter blant dei som bruker tobakk og/eller vape i ulike aldersgrupper, 2025"
subtitle = "Bruker to ulike tobakksprodukt og/eller vape dagleg eller av og til"
caption = "Helsedirektoratet, tal frå Rus- og tobakksundersøkinga (SSB)"

drse <- dualDTAge[type2 == "rse"]
dualDX <- dualDTAge[dual != 3]

ddx <- rbindlist(list(dualDX, drse))
dd <- ddx[type2 != "rse"][alder != "Totalt"]


spec2 <- hd_spec(data = dd, x = "alder", y = "percentage", group = "type")
opt2 <- hd_opts(title = title, subtitle = subtitle, caption = caption, ylab = NULL, xlab = NULL, ysuffix = "%")
hd_make(spec2, "column", opt2)

```

## Figur 19 - alternativ

```{r}
# -------------------------------
# 2. Reshape to wide format
# -------------------------------
dtt_wide <- dcast(dualDTAge, alder ~ type2 + dual, value.var = "percentage")



# -------------------------------
# 3. Build stacked chart
# -------------------------------
highchart() |>
  hc_chart(type = "column") |>
  hc_xAxis(categories = dtt_wide$alder) |>
  hc_plotOptions(column = list(stacking = "normal")) |>
  hc_add_series(name = "Snus og sigarettar", data = dtt_wide$rs_1, stack = "stack1") |>
  hc_add_series(name = "Vape, snus og sigarettar", data = dtt_wide$rs_3, stack = "stack1") |>
  hc_add_series(name = "Vipe og sigarettar", data = dtt_wide$re_1, stack = "stack2") |>
  hc_add_series(name = "Vape, snus og sigarettar", data = dtt_wide$re_3, stack = "stack2") |>
  hc_add_series(name = "Vipe og snus", data = dtt_wide$se_1, stack = "stack3") |>
  hc_add_series(name = "Vape, snus og sigarettar", data = dtt_wide$se_3, stack = "stack3") |>
  hc_add_series(name = "Vape, snus og sigarettar", data = dtt_wide$rse_3, stack = "stack4") |>
  hc_title(text = title) |>
  hc_yAxis(title = list(text = "Value")) |>
  highcharter::hc_exporting(
    enabled       = TRUE,
    filename      = "highdir-figure",
    accessibility = list(enabled = TRUE)
  ) |>
  highcharter::hc_subtitle(
    text = subtitle
  ) |>
  highcharter::hc_caption(text = caption)


```
